### ISSUE TITLE
alias with special character symbols fails

### ISSUE THREAD

**Issue by obrie** [graalvm/truffleruby#148]
Passing symbols with special characters appears to not work.  However, it appears to only be a problem when defining a symbol with something like `:'props='` vs. `:props=`.  Note that this only affects `alias` --
 it doesn't affect `alias_method`.

For example:

```
ext-truffleruby :001 > class Foo1
ext-truffleruby :002?>     def props=(value)
ext-truffleruby :003?>       end
ext-truffleruby :004?>     alias :'properties=' :'props='
ext-truffleruby :005?>   end
RubyTruffleError: org.truffleruby.parser.ast.SymbolParseNode cannot be cast to org.truffleruby.parser.ast.LiteralParseNode
	ClassCastException org.truffleruby.parser.BodyTranslator.translateNameNodeToSymbol(BodyTranslator.java:306)
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/workspace.rb:87:in `eval'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/workspace.rb:87:in `evaluate'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/context.rb:380:in `evaluate'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:489:in `block (2 levels) in eval_input'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:623:in `signal_status'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:486:in `block in eval_input'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:232:in `loop'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:231:in `catch'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:231:in `catch'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:231:in `register'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:231:in `catch'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb/ruby-lex.rb:231:in `each_top_level_statement'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:485:in `eval_input'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:395:in `block in start'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:394:in `catch'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:394:in `catch'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:394:in `register'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:394:in `catch'
	from /home/aaron/Projects/truffle/truffleruby/lib/mri/irb.rb:394:in `start'
	from /home/aaron/.rvm/rubies/ext-truffleruby/bin/irb:15:in `<main>'
Maybe IRB bug!
ext-truffleruby :006 > 
ext-truffleruby :007 >   class Foo2
ext-truffleruby :008?>     def props=(value)
ext-truffleruby :009?>       end
ext-truffleruby :010?>     alias :properties= :props=
ext-truffleruby :011 >     end
 => Foo2 
ext-truffleruby :012 > 
ext-truffleruby :013 >   class Foo3
ext-truffleruby :014?>     def props=(value)
ext-truffleruby :015?>       end
ext-truffleruby :016?>     alias_method :'properties=', :'props='
ext-truffleruby :017?>   end
 => Foo3 
ext-truffleruby :018 > 
ext-truffleruby :019 >   class Foo4
ext-truffleruby :020?>     def props=(value)
ext-truffleruby :021?>       end
ext-truffleruby :022?>     alias_method :properties=, :props=
ext-truffleruby :023?>   end
 => Foo4 
```

This was tested with the following version of truffleruby: https://github.com/graalvm/truffleruby/commit/3896217bbb457b73eb3db75d1ed5c2deb5be95d2

**Comment by chrisseaton** [comment]
Thanks for this - you found language functionality which wasn't covered by the specs.

Specs added in 0dc70c1584a91b2804008c8ab7619f5634019471.

Fix in 21c1a003f122af3d3af345bdf42ff27adc15a4b6.
