### ISSUE TITLE
Chruby

### ISSUE THREAD

**Issue by timuckun** [graalvm/truffleruby#30]
I use chruby so I thought I would try it with Graalvm. I went to the oracle site and downloaded the tar file. I untarred it and put it in the ~/.rubies directory.  Since there is a bin/ruby in the graalvm directory I thought it might "just work".

When I attempt to chruby graalvm I get an error

```bash
Exception in thread "main" org.jruby.truffle.language.control.RaiseException: internal implementation error -
IOException Can't read file - org.jruby.truffle.language.loader.SourceLoader.ensureReadable(SourceLoader.java:106)
```

I wasn't really thinking it would work but it almost did so I thought I'd tell you guys about it.

**Comment by eregon** [comment]
Thank you for the report! I am also a chruby user.
The problem above is due to chruby executing `bin/ruby` with `-` and input on stdin:
https://github.com/postmodern/chruby/blob/d02904da6d5b634845bd42639e3a4c80fd8bfc78/share/chruby/chruby.sh#L46
This has been already fixed on latest truffleruby, but was not yet in GraalVM 0.19.
The next release, GraalVM 0.20, should be available beginning of February and fix this.

Another option would be to build this repo:
```bash
git clone https://github.com/graalvm/truffleruby.git
tool/jt.rb build
cd bin && ln -s truffleruby ruby
```

Then you can add that folder in `~/.rubies`:
```bash
cd ~/.rubies
ln -s path/to/trufflerubyrepo truffleruby
```

Open a new terminal and:
```bash
chruby truffleruby
ruby -v
```

**Comment by timuckun** [comment]
Thanks. That worked (but I still have to upgrade my JVM).  One thing. I have 

JRUBY_OPTS=--dev

so it complains 

jruby: unknown option --dev

I had to remove that from the env.

**Comment by eregon** [comment]
Great!

This is just  a warning, so only worry if you want to measure performance.
Upgrading the JVM is not quite enough currently.
Since you know have your own build of truffleruby, you also need your own build of Graal if you want to run with Graal, see https://github.com/graalvm/truffleruby/blob/truffle-head/doc/contributor/building-graal.md.

Re `JRUBY_OPTS`, we are going to ingore that variable in a couple days, so it should no longer be a problem. (We will have `TRUFFLERUBYOPT` instead.)

**Comment by timuckun** [comment]
Something else seems to be wrong. I think it's tripping over gems or something. 

This is from the graal install from the Oracle site not the one I built according to the instructions above

```bash
./ruby -S gem install bundler
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring bcrypt-3.1.7 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.7
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
Ignoring byebug-9.0.5 because its extensions are not built.  Try: gem pristine byebug --version 9.0.5
Ignoring byebug-8.2.2 because its extensions are not built.  Try: gem pristine byebug --version 8.2.2
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring eventmachine-1.2.0.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.0.1
Ignoring ffi-1.9.14 because its extensions are not built.  Try: gem pristine ffi --version 1.9.14
Ignoring hitimes-1.2.4 because its extensions are not built.  Try: gem pristine hitimes --version 1.2.4
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring io-console-0.4.6 because its extensions are not built.  Try: gem pristine io-console --version 0.4.6
Ignoring json-2.0.1 because its extensions are not built.  Try: gem pristine json --version 2.0.1
Ignoring lmdb-0.4.8 because its extensions are not built.  Try: gem pristine lmdb --version 0.4.8
Ignoring msgpack-1.0.2 because its extensions are not built.  Try: gem pristine msgpack --version 1.0.2
Ignoring nio4r-1.2.1 because its extensions are not built.  Try: gem pristine nio4r --version 1.2.1
Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Ignoring oj-2.18.0 because its extensions are not built.  Try: gem pristine oj --version 2.18.0
Ignoring pg-0.19.0 because its extensions are not built.  Try: gem pristine pg --version 0.19.0
Ignoring psych-2.1.0 because its extensions are not built.  Try: gem pristine psych --version 2.1.0
Ignoring puma-3.6.0 because its extensions are not built.  Try: gem pristine puma --version 3.6.0
Ignoring puma-3.5.0 because its extensions are not built.  Try: gem pristine puma --version 3.5.0
Ignoring puma-3.4.0 because its extensions are not built.  Try: gem pristine puma --version 3.4.0
Ignoring sqlite3-1.3.12 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.12
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring websocket-driver-0.6.4 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.4
(core):1:in `require':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': cannot load such file -- psych.so (LoadError)
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tim/.gem/ruby/2.3.1/gems/psych-2.1.0/lib/psych.rb:7:in `<main>'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/yaml.rb:6:in `<main>'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems.rb:700:in `load_yaml'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/config_file.rb:340:in `load_file'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/config_file.rb:202:in `initialize'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/gem_runner.rb:75:in `new'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/gem_runner.rb:75:in `do_configuration'
	from /Users/tim/.rubies/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/gem_runner.rb:40:in `run'
	from /Users/tim/.rubies/truffleruby/bin/gem:21:in `<main>'
```

Brew search libyaml shows that I have it installed already.

**Comment by eregon** [comment]
We support bundler with some workarounds, which need to be documented and maybe simplified.
This is tracked by #17.

In this case it seems the wrong GEM_HOME is used. I think it's set in your environment to be the one of MRI 2.3.1 by chruby.
I am not sure what we should in this case, but GraalVM should probably set its own GEM_HOME so this does not happen.

**Comment by timuckun** [comment]
Yes chruby does set GEM_HOME, it seems like it should set it's GEM_HOME just to be safe.

**Comment by eregon** [comment]
I'll close this in favor of #59 which tries to address the GEM_HOME issues.
