### ISSUE TITLE
Can't run rails tests

### ISSUE THREAD

**Issue by kirs** [graalvm/truffleruby#426]
```
$ jt test ecosystem activemodel
jtt: $ GEM_HOME="~/opensource/truffleruby-ws/truffleruby/truffleruby-gem-test-pack-1/gems" GEM_PATH="~/opensource/truffleruby-ws/truffleruby/truffleruby-gem-test-pack-1/gems" ~/opensource/truffleruby-ws/truffleruby/bin/truffleruby ~/opensource/truffleruby-ws/truffleruby/truffleruby-gem-test-pack-1/gems/bin/bundle install --local --no-prune --without db\ job
Resolving dependencies....................
Could not find rake-10.4.2 in any of the sources
jtt: RuntimeError: command failed\n~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:57:in `execute_cmd'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:764:in `execute_cmd'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:614:in `subcommand_setup'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:449:in `send'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:449:in `block in run'
~/opensource/truffleruby-ws/truffleruby/src/main/ruby/core/dir.rb:207:in `chdir'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:447:in `run'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:911:in `block in setup'
~/opensource/truffleruby-ws/truffleruby/src/main/ruby/core/dir.rb:207:in `chdir'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:910:in `setup'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/config.rb:237:in `rails_ci_setup'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/config.rb:221:in `rails_ci'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/config.rb:275:in `block in <top (required)>'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:843:in `instance_eval'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:843:in `block in do_definition'
~/opensource/truffleruby-ws/truffleruby/src/main/ruby/core/throw_catch.rb:34:in `catch'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:841:in `do_definition'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:832:in `initialize'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:748:in `new'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:748:in `subcommand_ci'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:449:in `send'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:449:in `block in run'
~/opensource/truffleruby-ws/truffleruby/src/main/ruby/core/dir.rb:207:in `chdir'
~/opensource/truffleruby-ws/truffleruby/lib/truffleruby-tool/lib/truffle_tool.rb:447:in `run'
lib/truffleruby-tool/bin/truffleruby-tool:6:in `<main>'

```

This is somewhat weird because `rake-10.4.2` is present in `truffleruby-gem-test-pack-1`.

**Comment by kirs** [comment]
Assuming that it works on CI, maybe there is something wrong with my local environment? Can anyone confirm that it works for them?

**Comment by eregon** [comment]
This works on CI and locally for me.
Maybe you have `TRUFFLERUBY_RESILIENT_GEM_HOME` set in your environment?
This is currently clashing with it, I pushed a fix for it in https://github.com/graalvm/truffleruby/pull/430.

**Comment by pitr-ch** [comment]
Works for me locally as well.

**Comment by kirs** [comment]
I don't have `TRUFFLERUBY_RESILIENT_GEM_HOME` set.
Thanks for confirming. Us must be something wrong in my environment.
