### ISSUE TITLE
TruffleFatalException: couldn't load the post-boot code

### ISSUE THREAD

**Issue by mensfeld** [graalvm/truffleruby#452]
Hey guys, I've followed all of your instructions, installed truffleruby, compiled sulong add added it to support C extensions, but I can't get pass that problem :(

```bash
/home/mencio/.rvm/rubies/ruby-2.4.1/bin/ruby ../truffleruby/tool/jt.rb test test :capi

$ EXCLUDES=test/mri/excludes RUBYOPT=--disable-gems /home/mencio/.graalvm/truffleruby/bin/truffleruby -Xcore.load_path=/home/mencio/.graalvm/truffleruby/src/main/ruby -Xgraal.warn_unless=false -Xexceptions.print_uncaught_java=true -J-Xmx2G -J-ea -J-esa test/mri/tests/runner.rb -v --color=never --tty=no -q test :capi
/home/mencio/.graalvm/truffleruby/src/main/ruby/post-boot/post-boot.rb:17:in `method_missing': undefined method `print_time_metric' for Truffle::Boot:Module (NoMethodError)
	from /home/mencio/.graalvm/truffleruby/src/main/ruby/post-boot/post-boot.rb:17:in `<top (required)>'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.graalvm.launcher.LegacyLauncher.main(stripped:20)
Caused by: org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.TruffleFatalException: couldn't load the post-boot code
FAILED (pid 23582 exit 1): EXCLUDES=test/mri/excludes RUBYOPT=--disable-gems /home/mencio/.graalvm/truffleruby/bin/truffleruby -Xcore.load_path=/home/mencio/.graalvm/truffleruby/src/main/ruby -Xgraal.warn_unless=false -Xexceptions.print_uncaught_java=true -J-Xmx2G -J-ea -J-esa test/mri/tests/runner.rb -v --color=never --tty=no -q test :capi
```

**Comment by eregon** [comment]
Hello,
I think you made a typo in the command (there is `test` 2 times):
```
/home/mencio/.rvm/rubies/ruby-2.4.1/bin/ruby ../truffleruby/tool/jt.rb test test :capi
```
It should be:
```
/home/mencio/.rvm/rubies/ruby-2.4.1/bin/ruby ../truffleruby/tool/jt.rb test :capi
```

**Comment by mensfeld** [comment]
Hello @eregon, thank you for your help. Unfortunately it doesn't help. I probably  did a typo when copying stuff.

Here's a single "test" example:

```bash
/home/mencio/.rvm/rubies/ruby-2.4.1/bin/ruby ../truffleruby/tool/jt.rb test :capi
$ /home/mencio/.graalvm/truffleruby/bin/truffleruby -Xcore.load_path=/home/mencio/.graalvm/truffleruby/src/main/ruby -Xgraal.warn_unless=false spec/mspec/bin/mspec run --config spec/truffle.mspec --excl-tag fails :capi
/home/mencio/.graalvm/truffleruby/src/main/ruby/post-boot/post-boot.rb:17:in `method_missing': undefined method `print_time_metric' for Truffle::Boot:Module (NoMethodError)
	from /home/mencio/.graalvm/truffleruby/src/main/ruby/post-boot/post-boot.rb:17:in `<top (required)>'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.graalvm.launcher.LegacyLauncher.main(stripped:20)
Caused by: org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.TruffleFatalException: couldn't load the post-boot code
```

**Comment by eregon** [comment]
Did you rebuild after cloning or pulling?
You can do it with:
```
tool/jt.rb build
```
This looks like it's using an old compiled version of TruffleRuby.
You might also want to run tests from truffleruby's directory if not already the case:
```
/home/mencio/.rvm/rubies/ruby-2.4.1/bin/ruby /tool/jt.rb test :capi
```

**Comment by eregon** [comment]
Actually the backtrace shows you are using GraalVM somehow (com.oracle.graalvm.launcher.LegacyLauncher).
Make sure GRAALVM_BIN and RUBY_BIN and GRAAL_HOME are all unset in your environment.

If you just want to use GraalVM's bin/ruby, there is no need for cloning truffleruby.

**Comment by mensfeld** [comment]
@eregon  thank you for your help. I will close that one as it seems it is not truffleruby related but more about mine setup and mistakes I did during the installation and compilation process. Thank you once again for your help.

**Comment by eregon** [comment]
@mensfeld Glad I could help. Was it just the missing `jt build`?

**Comment by mensfeld** [comment]
@eregon  yeah. I still have some problems with the native extensions (some like hitimes), but it's an early stage, so I don't expect everything to work :-)

Great job btw!

**Comment by eregon** [comment]
Right, we only tried a couple C-exts so far (openssl, sysylog, zlib, puma, some db drivers, etc).
However, please report issues you run into, it's always good to know what users want to run and there might be an easy fix.
